# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SN-qqVxWgZlUNsY7mDPbxUMwXr330XOy
"""



funcionarios = {}

def adicionar_funcionario():
    print("Adicionar novo Funcionário")
    nome = input("Informe o nome do Funcionário: ")
    id_funcionario = input("Informe o ID do Funcionário: ")
    setor = input("Informe o setor: ")
    if id_funcionario in funcionarios:
        print("Já existe um funcionário com essa Identificação")
    else:
        funcionarios[id_funcionario] = {"nome": nome, "setor": setor}
        print("Funcionário Adicionado a Equipe")

def remover_funcionario():
    print("Remover funcionário da Equipe")
    id_funcionario = input("Informe o ID do funcionário Desejado: ")
    if id_funcionario in funcionarios:
        del funcionarios[id_funcionario]
        print("Funcionário Apagado")
    else:
        print("Não existe nem um funcionário com essa Identificação")

def alterar_setor():
    print("Alterar setor do funcionário")
    id_funcionario = input("Informe o ID do funcionário: ")
    if id_funcionario in funcionarios:
        novo_setor = input("Informe o novo setor do funcionário: ")
        funcionarios[id_funcionario]["setor"] = novo_setor
        print("Setor Alterado")
    else:
        print("Não existe nem um funcionário com essa Identificação")

def listar_funcionarios():
    print("Lista - Funcionários")
    for id_funcionario, dados_funcionario in funcionarios.items():
        print(f"ID: {id_funcionario} | Nome: {dados_funcionario['nome']} | Setor: {dados_funcionario['setor']}")

def main():
    print("Bem Vindo ao controle de acesso")

    while True:
        print("\n1 - Adicionar funcionário")
        print("2 - Remover funcionário")
        print("3 - Alterar setor do funcionário")
        print("4 - Listar funcionários")
        print("0 - Sair")

        opcao = input("Informe a opção desejada: ")

        if opcao == "1":
            adicionar_funcionario()
        elif opcao == "2":
            remover_funcionario()
        elif opcao == "3":
            alterar_setor()
        elif opcao == "4":
            listar_funcionarios()
        elif opcao == "0":
            print("Saindo do controle de acesso...")
            break
        else:
            print("Opção inválida")
main()