# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SN-qqVxWgZlUNsY7mDPbxUMwXr330XOy
"""

from collections import deque

a = 0

clientes = deque()

triagem = []

atendidos = []



def adicionar_Clientes(lista):
    triagem.append(lista)
    clientes.append(lista)
    
    print (lista, "entrou na fila \n")

def dis_Removido(lista):
    return atendidos[lista]

def remover_Cliente():
    atendidos.append(clientes.popleft())
    
    print (dis_Removido(0), "O Cliente foi Atendido!")

while (a == 0):
  novo_Cliente = input('Se Deseja Prosseguir digite (Proximo): \nCaso queira Adicionar um Cliente digite o nome: ')

  if (novo_Cliente == "Proximo"):
    break

  else:
    adicionar_Clientes(novo_Cliente)
  deletar_Cliente = input('Para remover o cliente que será atendido, digite (Deletar) \nSe Deseja Prosseguir digite (Proximo): ')
  
  if (deletar_Cliente != "Proximo"):
    remover_Cliente()
  Fila = input('Para consultar a fila digite (Fila) \nSe Deseja Encerrar a operação digite (Cancelar): ')
  
  if (Fila == "Cancelar"):
    break
 
  else:
    print(clientes)