# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SN-qqVxWgZlUNsY7mDPbxUMwXr330XOy
"""

from datetime import datetime


def estoque_produto(lista):
   produtos_ordenados = sorted(lista, key=lambda listaproduto: listaproduto["data_entrada"])
   return produtos_ordenados

def entrada_produto():
    nomeproduto = input("Insira o nome do produto:")
    quantproduto = int(input("Insira a quantida de produto"))





estoque_de_produto = [
    {"produto": "Cimento", "data_entrada": datetime(2023, 2, 3), 'qtd': 4, "validade": datetime(2023, 3, 4)}, 
    {"produto": "Prego", "data_entrada": datetime(2023, 1, 1), 'qtd': 8, "validade": datetime(2023, 2, 1)}, 
    {"produto": "Telha", "data_entrada": datetime(2023, 2, 2), 'qtd': 8, "validade": datetime(2023, 3, 4)},
]

estoque_produto(estoque_de_produto)

def cadastrar_produto():
   produto = {}
   produto["produto"] = input("Produto: ")
   print("Data de entrada")
   dia_entrada = int(input("Dia: "))
   mes_entrada = int(input("Mes: "))
   ano_entrada = int(input("Ano: "))
   produto["data_entrada"] = datetime(ano_entrada, mes_entrada, dia_entrada)
   produto["qtd"] = int(input("Quantidade: "))
   print("Validade")
   dia_entrada = int(input("Dia: "))
   mes_entrada = int(input("Mes: "))
   ano_entrada = int(input("Ano: "))
   produto["validade"] = datetime(ano_entrada, mes_entrada, dia_entrada)
   return estoque_de_produto.append(produto)



def vender_produto():
   estoque_produto(estoque_de_produto)

   i = 0
   for produto in estoque_de_produto:
      print(i,end=" ")
      print(f"Produto: {produto['produto']} / Data de Entrada: {produto['data_entrada']}, / Quantidade: {produto['qtd']} / Validade: {produto['validade']}")
      i += 1

   remover = int(input("Qual deseja remover [Digite o número]: "))
   if (estoque_de_produto[remover]["qtd"]) > 0:
      estoque_de_produto[remover]["qtd"] = estoque_de_produto[remover]["qtd"] -1
   if estoque_de_produto[remover]["qtd"] == 0:
      estoque_de_produto.pop(remover)